[package]
name = "maxbuild"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
bytes = "1.9.0"
clap = { version = "4.5.23", features = ["derive"] }
anyhow = "1.0.95"
