name: Release

on:
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    uses: ./.github/workflows/rust.yml
  release:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu, macos, windows ]
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        path: ${{ github.workspace }}/artifacts/
    - name: List Artifact
      id: list_artifact
      run: echo "artifact_path=`ls ${{ github.workspace }}/artifacts/maxbuild-${{ matrix.os }}/*`" >> $GITHUB_OUTPUT
    - name: Pack Artifact
      run: zip ${{ github.workspace }}/maxbuild-${{ matrix.os }}.zip ${{ steps.list_artifact.outputs.artifact_path }}
    - name: Upload to Release Action
      uses: Shopify/upload-to-release@v2.0.0
      with:
        name: maxbuild-${{ matrix.os }}.zip
        path: ${{ github.workspace }}/maxbuild-${{ matrix.os }}.zip
        repo-token: ${{ secrets.GITHUB_TOKEN }}
