name: Release

on:
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    uses: ./.github/workflows/rust.yml
  release:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu, macos]
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        path: ${{ github.workspace }}/artifacts/
    - name: List Artifacts
      run: |
        export ARTIFACT_PATH=$(find ${{ github.workspace }}/artifacts/maxbuild*)
    - name: Upload to Release Action
      uses: Shopify/upload-to-release@v2.0.0
      with:
        name: maxbuild-${{ matrix.os }}
        path: ${{ env.ARTIFACT_PATH }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
