name: Rust

on:
  push:
    branches: [ "main", "github-actions-setup" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        name: maxbuild-${{ matrix.os }}
        path: target/release/maxbuild*
          
